### ISSUE TITLE
It does not process adequately GIF87a

### ISSUE THREAD

**Issue by studiosi** [MrFlick/whats-in-a-gif#3]
This is a common occurence when processing GIFs, but I think it chokes with the original GIF specification. I have attached a test GIF that can be used for testing. I am happy to provide more information. I am not sure if Github manipulates the image in some way, so if you need it I would be more than happy to provide it.

= ERROR =

Unexpected block type: 0x71 @9162

![GIFTEST1](https://user-images.githubusercontent.com/423589/163693845-f9ea0ca6-9d85-448d-900e-b2f557e92bf9.GIF)

**Comment by MrFlick** [comment]
Thank you for providing this example. I can replicate the error with this GIF. I will look into this. Do you know the source of this image? Perhaps they have information on why this sample image might be different from other GIFs I've looked at.

**Comment by MrFlick** [comment]
I looked more into the file. According the the spec, the file should end when it encounters the terminator block. This file contains a terminator block 3B at offset 9,161. But then it has an additional 54 bytes after that. I can't find any documentation for how to decode those additional bytes. I've updated by GIF explorer to simply report those bytes as "trailing trivia". But it does appear to be an invalid file according to the spec.

**Comment by studiosi** [comment]
As far as I understand the terminator does not mean the file needs to end, but rather than the image ends. So my understanding is that the bytes after the terminator should just be ignored (I might be as well 100% wrong).

From https://www.w3.org/Graphics/GIF/spec-gif87.txt

"In order to provide a synchronization for the termination of a  GIF image  file,  a  GIF  decoder  will process the end of GIF mode when the character 0x3B hex or ';' is found after an image  has  been  processed. By  convention  the  decoding software will pause and wait for an action indicating that the user is ready to continue.  This may be  a  carriage return  entered  at  the  keyboard  or  a  mouse click.  For interactive applications this user action must  be  passed  on  to  the  host  as  a carriage  return  character  so  that the host application can continue. The decoding software will then typically leave graphics mode and resume any previous process."

It says "end of GIF mode", not end of file. The file is one test file from a BBS that I found while doing archeology, so it is original media from the time where GIF87a was popular. Back then it was common to download the test file to test your image viewing software.

Thanks for paying attention to this. I found your page very helpful to understand the LZW inside GIF and I am actively using it as I am writing a GIF87a decoder. 👍

**Comment by MrFlick** [comment]
I saw that paragraph as well, but to me that implies switching to an interactive mode to get user input. That doesn't explain why there are additional bytes in the file. There is no information on how those bytes should be decoded/interpreted as far as I can tell. There is nothing in the GIF spec that matches up to that byte sequence. So it looks more like an invalid file, but I supposed most decoders just ignore the invalid bits.

For now my sample decoder doesn't crash at least so I'll consider this matter closed. I won't update the documentation because there doesn't appear any authoritative reference that describes or allows additional data after the terminator block. Good luck with your own decoder!

**Comment by studiosi** [comment]
Yeah, that seems like a good compromise. I am not sure so as to what is there, but it seems that being a stream file it can be anything, I guess it is safe to ignore. If it does not crash and still provides the info that's golden!
