### ISSUE TITLE
“pallete is undefined” in ColorTableViewer

### ISSUE THREAD

**Issue by AndrewKvalheim** [MrFlick/whats-in-a-gif#4]
In case you’re interested, I just tried using the GIF Explorer and got this error message:

> #### GIF Draw Error
> 
> TypeError: pallete is undefined
> 
> Are you using an up-to-date browser? If so, there is probably a bug in the code :(

```
07:57:50.023 TypeError: pallete is undefined
    render https://www.matthewflickinger.com/lab/whatsinagif/scripts/gif_explorer_client.js:322
    init https://www.matthewflickinger.com/lab/whatsinagif/scripts/gif_explorer_client.js:310
    render https://www.matthewflickinger.com/lab/whatsinagif/scripts/gif_explorer_client.js:114
    render https://www.matthewflickinger.com/lab/whatsinagif/scripts/gif_explorer_client.js:111
    drawToc https://www.matthewflickinger.com/lab/whatsinagif/scripts/gif_explorer_client.js:1379
```

Firefox 126.0, [pngquant-interactive/screenshot.gif](https://codeberg.org/AndrewKvalheim/pngquant-interactive/src/commit/e87d3e2d2958771d22b2297d6adda551ce6e0fee/screenshot.gif)

**Comment by AndrewKvalheim** [comment]
Also `pallete` is misspelled, though consistently.

**Comment by MrFlick** [comment]
Thanks for the report and reproducible example. I tried in chrome and got a different error: "TypeError: Cannot read properties of undefined (reading '0')" and I'm also able to reproduce the same error as you in firefox as well. There must be something deeper than a poor spelling choice going on. I'll take a look.

**Comment by MrFlick** [comment]
OK. I found that I wasn't properly extracting the data for local color tables; my examples were only using a global color table. I've updated the code. Thanks for letting me know. It seems both Chrome and Firefox aggressively cache web worker scripts so I had to force refresh a few times to get the updated script, but when it finally got the new version it was able to parse the file you provided.
